### ISSUE TITLE
multiple files?

### ISSUE THREAD

**Issue by mark-hahn** [randy3k/remote-atom#2]
I haven't tried remote-atom yet.  The readme gives me the impression I have to give a command in the server to edit a single file.  Is there a way to choose multiple files to select from?

**Comment by loranger** [comment]
I had exactly the same question.
I tried to open multiple files using the rmate command installed years ago for textmate. And the first file only opened.
As the same command opens all the file in textmate2 (once remote-atom server is stoppped and textmate opened) I don't think that's an rmate client limitation which is weird because atom is able to open multiple files locally. It should be able to handle multiple files remotly once the server is active ?

**Comment by randy3k** [comment]
@loranger are you using the official ruby version of rmate? I was referring the bash version client.

**Comment by loranger** [comment]
Yep the ruby one.
I didn't know the features were not the same between the different versions.

Anyway as the ruby mate sends the full list of files, is there a way to open all of them inside atom at once ?

**Comment by randy3k** [comment]
Let me reopen the issue. It would take some work to enable it.

**Comment by loranger** [comment]
Awesome !
Thank you @randy3k !!

**Comment by randy3k** [comment]
Done e6066357c739922a8fd0334d8fb77528bdb62166.

**Comment by randy3k** [comment]
I also submitted a PR to bash-rmate for this support: https://github.com/aurora/rmate/pull/46.
